services:
  reverse-proxy:
    # The official v3 Traefik docker image
    image: traefik:v3.3
    # Enables the web UI and tells Traefik to listen to docker
    command:
      - --api.insecure=true
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --entryPoints.web.address=:80
    ports:
      # The HTTP port
      - 80:80
      # The Web UI (enabled by --api.insecure=true)
      - 8080:8080
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
  app:
    image: ghcr.io/cariboublue/top-spot:${APP_IMAGE_TAG:-latest}
    volumes:
      - /var/lib/sqlite:/var/lib/sqlite
    environment:
      ENV_FILES: /run/secrets/app_secrets
      SPOTIFY_REDIRECT_URI: http://shmoopysworld.com/auth/spotify/redirect
      DB_PATH: /var/lib/sqlite/db.sqlite
    secrets:
      - app_secrets
    labels:
      - traefik.enable=true
      - traefik.http.routers.app.rule=HostRegexp(`(www\.)?shmoopysworld\.com`)
      - traefik.http.routers.app.entrypoints=web
    deploy:
      mode: replicated
      replicas: 2
    restart: always
  sqlite:
    image: keinos/sqlite3
    volumes:
      - /var/lib/sqlite:/var/lib/sqlite
    command: sleep infinity
secrets:
  app_secrets:
    external: true
