services:
  reverse-proxy:
    # The official v3 Traefik docker image
    image: traefik:v3.3
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - 80:80
      # The Web UI (enabled by --api.insecure=true)
      - 8080:8080
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
  app:
    image: ghcr.io/cariboublue/top-spot:latest
    container_name: app
    volumes:
      - /var/lib/sqlite:/var/lib/sqlite
    environment:
      ENV_FILES: /run/secrets/app_secrets
      DB_PATH: /var/lib/sqlite/db.sqlite
      SPOTIFY_REDIRECT_URI: http://app.localhost/auth/spotify/redirect
    secrets:
      - app_secrets
    labels:
      - traefik.http.routers.app.rule=Host(`app.localhost`)
      - traefik.http.services.app.loadbalancer.server.port=80
  sqlite:
    image: keinos/sqlite3
    container_name: sqlite
    volumes:
      - /var/lib/sqlite:/var/lib/sqlite
    command: sleep infinity
secrets:
  app_secrets:
    file: .secrets
