services:
  reverse-proxy:
    # The official v3 Traefik docker image
    image: traefik:v3.3
    # Enables the web UI and tells Traefik to listen to docker
    command:
      - --api.insecure=true
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --entryPoints.websecure.address=:443
      - --certificatesresolvers.myresolver.acme.tlschallenge=true
      - --certificatesresolvers.myresolver.acme.email=${ACME_EMAIL}
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
    ports:
      # The HTTP port
      - 80:80
      # The Web UI (enabled by --api.insecure=true)
      - 8080:8080
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      # So that Traefik can store the ACME certs
      - letsencrypt:/letsencrypt
  app:
    image: ghcr.io/cariboublue/mixtape:${APP_IMAGE_TAG:-latest}
    volumes:
      - /var/lib/sqlite:/var/lib/sqlite
    environment:
      ENV_FILES: /run/secrets/app_secrets
      SPOTIFY_REDIRECT_URI: http://shmoopysworld.com/auth/spotify/redirect
      DB_PATH: /var/lib/sqlite/db.sqlite
    secrets:
      - app_secrets
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.app-ratelimit.ratelimit.average=20
      - traefik.http.routers.app.rule=HostRegexp(`(www\.)?shmoopysworld\.com`) && !Method(`POST`)
      - traefik.http.services.app.loadbalancer.server.port=80
      - traefik.http.routers.app.entrypoints=websecure
      - traefik.http.routers.app.tls.certresolver=myresolver
      - traefik.http.routers.app.middlewares=app-ratelimit
      # Define separate router for POST methods
      - traefik.http.middlewares.app-ratelimit-post.ratelimit.average=1
      - traefik.http.middlewares.app-ratelimit-post.ratelimit.period=1m
      - traefik.http.routers.app-post.rule=HostRegexp(`(www\.)?shmoopysworld\.com`) && Method(`POST`)
      - traefik.http.routers.app-post.middlewares=app-ratelimit-post
      - traefik.http.routers.app-post.entrypoints=websecure
      - traefik.http.routers.app-post.tls.certresolver=myresolver
    deploy:
      replicas: 2
  sqlite:
    image: keinos/sqlite3
    volumes:
      - /var/lib/sqlite:/var/lib/sqlite
    command: sleep infinity
volumes:
  letsencrypt:
secrets:
  app_secrets:
    external: true
