# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CONTAINER_REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  STACK_NAME: ${{ github.repository }}
  DOCKER_DEPLOY_HOST: ssh://deploy@${{ secrets.DEPLOY_HOST }}
  DOCKER_DEPLOY_PRIVATE_KEY: ${{ secrets.DEPLOY_SSH_SECRET_KEY }}

jobs:

  build-app:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4.2.0

    - name: Install node dependencies
      run: npm install

    - name: Generate css
      run: npx tailwindcss -i ./static/css/input.css -o ./static/css/output.css
      
    - name: Set up Docker
      uses: docker/setup-docker-action@v4.1.0

    - name: Login to docker
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3.3.0
      with:
        registry: ${{ env.CONTAINER_REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Generate image metadata
      id: meta
      uses: docker/metadata-action@v5.6.1
      with:
        images: ${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
    
    - name: Build and push app image
      uses: docker/build-push-action@v6.14.0
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
              
  deploy-app:
    runs-on: ubuntu-latest

    needs:
      - build-app

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Deploy app stack
      uses: cssnr/stack-deploy-action@v1
      with:
        name: ${{ env.STACK_NAME }}
        file: ./compose.yaml
        host: ${{ env.DOCKER_DEPLOY_HOST }}
        ssh-key: ${{ env.DOCKER_DEPLOY_PRIVATE_KEY }}
        registry_auth: true
